# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('consumer_number', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=10)),
                ('landline_number', models.CharField(max_length=10)),
                ('complaint_type', models.CharField(choices=[(None, 'Select the type of Complaint'), ('LEAK', 'Leakage Problem'), ('LATE', 'Late Delivery'), ('MAN', 'Complaint against Delivery Man'), ('STAFF', 'Complaint against Office Staff'), ('OTHERS', 'Other')], default=None, max_length=2)),
                ('address', models.CharField(max_length=280)),
                ('complaint_detail', models.CharField(max_length=200)),
            ],
        ),
    ]
