# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[(None, 'Select the type of Complaint'), ('LEAK', 'Leakage Problem'), ('LATE', 'Late Delivery'), ('MAN', 'Complaint against Delivery Man'), ('STAFF', 'Complaint against Office Staff'), ('OTHERS', 'Other')], default=None, max_length=6),
        ),
    ]
