# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, editable=False, max_length=70),
        ),
    ]
