# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-11 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sender_email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=280)),
                ('query', models.CharField(max_length=200)),
            ],
        ),
    ]
