# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='query',
            field=models.TextField(max_length=200),
        ),
    ]
