# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-27 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0002_auto_20180312_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='query',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sender_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
